[Core]
  IP = "0.0.0.0"
  RPCPort = "26657"
  GRPCPort = "0"

[State]
  KeyringAccName = ""

[P2P]
  ListenAddresses = ["/ip4/0.0.0.0/udp/2121/quic-v1", "/ip6/::/udp/2121/quic-v1", "/ip4/0.0.0.0/tcp/2121", "/ip6/::/tcp/2121"]
  AnnounceAddresses = []
  NoAnnounceAddresses = ["/ip4/0.0.0.0/udp/2121/quic-v1", "/ip4/127.0.0.1/udp/2121/quic-v1", "/ip6/::/udp/2121/quic-v1", "/ip4/0.0.0.0/tcp/2121", "/ip4/127.0.0.1/tcp/2121", "/ip6/::/tcp/2121"]
  Bootstrapper = false
  MutualPeers = []
  PeerExchange = false
  RoutingTableRefreshPeriod = "1m0s"
[P2P.ConnManager]
  Low = 50
  High = 100
  GracePeriod = "1m0s"

[RPC]
  Address = "0.0.0.0"
  Port = "26658"

[Gateway]
  Address = "0.0.0.0"
  Port = "26659"
  Enabled = false

[Share]
  PeersLimit = 3
  DiscoveryInterval = "30s"
  AdvertiseInterval = "30s"

[Header]
  TrustedHash = ""
  TrustedPeers = []
[Header.Store]
  StoreCacheSize = 4096
  IndexCacheSize = 16384
  WriteBatchSize = 2048
[Header.Syncer]
  TrustingPeriod = "168h0m0s"
  MaxRequestSize = 512
[Header.Server]
  WriteDeadline = "5s"
  ReadDeadline = "1m0s"
  MaxRequestSize = 512
  RequestTimeout = "5s"