commonLabels:
  chain_id: test-1
  environment: test
  network: consensus
  type: full

persistence:
  size: 30Gi
  # dataSource:
  #   apiGroup: snapshot.storage.k8s.io
  #   kind: VolumeSnapshot
  #   name: consensus-latest
app:
  secret:
    name: consensus-1
  resources:
    requests:
      cpu: 2
      memory: 8Gi
    limits:
      cpu: 2
      memory: 8Gi
  settings:
    genesisURL: "http://10.44.143.2:26657/genesis"
  config:
    clienttoml:
      chain_id: "test-1"
      node: "tcp://0.0.0.0:26657"
    configtoml:
      p2p:
        persistent_peers: "7aaed043cf5498032d4e7d0f146bc15f02bb476d@10.44.143.2:26656"
      instrumentation:
        prometheus: true
        pyroscope_url: "http://pyroscope:4040"
        pyroscope_tracing: true
      tx_index:
        indexer: "kv"
      rpc:
        max_subscriptions_per_client: 1000
  otelAgent:
    enabled: true
    grafanaOtelSecret:
      name: grafana-otel-token
diagnosticMode:
  enabled: false
