apiVersion: v1
kind: Service
metadata:
  name: {{ include "full.fullname" . }}
  labels:
    {{- include "full.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "full.selectorLabels" . | nindent 4 }}
