# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: celestia
  licenses: Apache-2.0
apiVersion: v2
appVersion: v1.9.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Celestia App
home: https://celestia.org
icon: https://celestia.org/img/celestia-logo.png
keywords:
  - celestia
  - celestia-app
maintainers:
  - name: Celestia Labs
    url: https://github.com/celestiaorg/celestia-helm-charts
name: celestia-app
sources:
  - https://github.com/celestiaorg/celestia-app
version: 0.1.0
