apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appInitContainer.configmapName }}
  namespace: {{ tpl .Values.global.namespace . }}
  labels:
    {{- toYaml .Values.global.labels | trim | nindent 4 }}
data:
{{- $path := "files/" }}
{{- $ctx := . }}
{{- range $filePath, $bytes := .Files.Glob (printf "%s**" $path) }}
  {{- $file := replace $path "" $filePath }}
  {{- $safeFile := replace "/" "_" $file }}  # Replace '/' with '_'
  {{- $safeFile | nindent 2 }}: |
{{ $ctx.Files.Get $filePath | nindent 4 }}
{{- end }}
