---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.celestiaApp.home.volume.name . }}
  namespace: {{ tpl .Values.global.namespace . }}
  labels:
    {{- toYaml .Values.global.labels | trim | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.celestiaApp.home.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.celestiaApp.home.volume.storage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.celestiaApp.home.configVolume.name . }}
  namespace: {{ tpl .Values.global.namespace . }}
spec:
  accessModes:
    - {{ .Values.celestiaApp.home.configVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.celestiaApp.home.configVolume.storage }}