{{ range .Values.celestiaApp.ports }}
{{- $file_name := .name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- toYaml $.Values.global.labels | trim | nindent 4 }}
  name: {{ .name }}
  namespace: {{ tpl $.Values.global.namespace $ }}
spec:
  ports:
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .port }}
  selector:
    app: celestia-app
  {{- if or (eq $file_name "p2p") (and (eq $file_name "rpc") $.Values.celestiaApp.rpcLoadBalancer) }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
{{ end }}
