name: Snyk Infrastructure as Code

on:
  push:
    branches: [ "sysrex/add_snyk_integration" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '24 8 * * 4'

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  snyk:
    name: Run Snyk to check the helm charts
    runs-on: ubuntu-latest

    steps:
      - name: Run Snyk to check configuration files for security issues
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Generate the Helm Template
        run: |
          helm template charts/app/ --output-dir ./output/app
          helm template charts/node/ --output-dir ./output/node

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name : Setup Go
        uses: actions/setup-go@v4

      - name: Snyk Helm Scanner Celestia
        run: |
          snyk iac test ./output/ --sarif-file-output=snyk.sariff
          ls
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif